version: '3.8'
services:
  postgres:
    image: postgres:13.12-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5433'
    environment:
      - TZ=Etc/UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  redis:
    image: redis:7.0.13-alpine
    command: redis-server
    ports:
      - '6379:6379'
