/* eslint-disable react/no-unescaped-entities */
import { DialogTitle } from "@radix-ui/react-dialog"
import { useState } from "react"

import { Dialog, DialogContent, DialogHeader } from "../ui/dialog"
import { Input } from "../ui/input"
import { ScrollArea } from "../ui/scroll-area";

interface FrequentTermsDialogProps {
    frequentTermsModalOpen: boolean;
    setFrequentTermsModalOpen: React.Dispatch<React.SetStateAction<boolean>>;
    frequentTermsData: {
        autoGenerated: string;
        edited: string;
    };
}

const FrequentTermsDialog = ({ frequentTermsModalOpen, setFrequentTermsModalOpen, frequentTermsData }: FrequentTermsDialogProps) => {
    const [searchTerm, setSearchTerm] = useState("")

    const autoGeneratedTermsArray = frequentTermsData?.autoGenerated?.split(',').map(term => term.trim()) || []
    const editedTermsArray = frequentTermsData?.edited?.split(',').map(term => term.trim()) || []

    const filteredAutoGeneratedTerms = autoGeneratedTermsArray.filter(term => term.toLowerCase().includes(searchTerm.toLowerCase()))
    const filteredEditedTerms = editedTermsArray.filter(term => term.toLowerCase().includes(searchTerm.toLowerCase()))

    return (
        <Dialog open={frequentTermsModalOpen} onOpenChange={setFrequentTermsModalOpen}>
            <DialogContent className="p-0 gap-0">
                <DialogHeader className="sticky top-0 bg-white border-b border-gray-200 p-4">
                    <DialogTitle className="text-xl font-semibold mb-4">Frequent Terms</DialogTitle>
                    <Input
                        type="text"
                        placeholder="Enter a term to lookup"
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="h-7 md:w-1/2 self-center"
                    />
                </DialogHeader>
                <ScrollArea className="h-[70vh] p-4 pt-2">
                    <div>
                        <h2 className="text-md font-semibold">Shortlisted:</h2>
                        <div className="flex flex-wrap gap-2 mt-2">
                            {filteredEditedTerms.length > 0 ? (
                                filteredEditedTerms.map((term, index) => (
                                    <span
                                        key={index}
                                        className="inline-block py-1 px-2 bg-gray-100 rounded text-sm shadow-sm"
                                    >
                                        {term}
                                    </span>
                                ))
                            ) : (
                                searchTerm ? (
                                    <p className="text-sm text-gray-500">No shortlisted terms found for "{searchTerm}".</p>
                                ) : (
                                    <p className="text-sm text-gray-500">No shortlisted terms available.</p>
                                )
                            )}
                        </div>
                    </div>
                    <div className="mt-5">
                        <h2 className="text-md font-semibold">Autogenerated:</h2>
                        <div className="flex flex-wrap gap-2 mt-2">
                            {filteredAutoGeneratedTerms.length > 0 ? (
                                filteredAutoGeneratedTerms.map((term, index) => (
                                    <span
                                        key={index}
                                        className="inline-block py-1 px-2 bg-gray-100 rounded text-sm shadow-sm"
                                    >
                                        {term}
                                    </span>
                                ))
                            ) : (
                                searchTerm ? (
                                    <p className="text-sm text-gray-500">No autogenerated terms found for "{searchTerm}".</p>
                                ) : (
                                    <p className="text-sm text-gray-500">No autogenerated terms available.</p>
                                )
                            )}
                        </div>
                    </div>
                </ScrollArea>
            </DialogContent>
        </Dialog>
    );
};

export default FrequentTermsDialog