name: Deploy to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model name (e.g., scribie/parakeet-tdt-speaker-diarization)'
        required: false
        default: 'scribie/parakeet-tdt-speaker-diarization'
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Replicate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install latest Cog
        run: |
          python -m pip install --upgrade pip
          pip install cog==0.9.8

      - name: Push to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}
        run: |
          echo "🚀 Deploying to Replicate..."
          cog push r8.im/${{ inputs.model_name || 'scribie/parakeet-tdt-speaker-diarization' }} 