name: Deploy to Replicate

on:
  workflow_dispatch: {}  # allow manual trigger
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        run: |
          echo "🚀 Deploying to Replicate..."
          cog push r8.im/scribie/parakeet-tdt-speaker-diarization 