name: Deploy to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model name (e.g., scribie/parakeet-tdt-speaker-diarization)'
        required: false
        default: 'scribie/parakeet-tdt-speaker-diarization'
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Replicate
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          echo "🚀 Deploying to Replicate..."
          HUGGINGFACE_TOKEN="${{ secrets.HUGGINGFACE_TOKEN }}" cog push r8.im/${{ inputs.model_name || 'scribie/parakeet-tdt-speaker-diarization' }} 