name: Gitleaks

on:
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Gitleaks action
        uses: zricethezav/gitleaks-action@v1.6.0
